### PR TITLE
new instance

### PR DESCRIPTION
**Pull request by osarthak**
add librey.org

### CODE REVIEW

**Comment by Ahwxorg** [comment]
Please remove config.php, opensearch.xml from your commit as those are local.

Why do you change code in i.e. instances.json that's perfectly fine? It seems like nothing has changed at all but GitHub shows changes?

**Comment by codedipper** [comment]
> Please remove config.php, opensearch.xml from your commit as those are local.
> 
> Why do you change code in i.e. instances.json that's perfectly fine? It seems like nothing has changed at all but GitHub shows changes?

When you edit it in vim or something that might do automated indentation, it'll mess things up. Either way, I'll add the instance properly in another PR because this is triggering what little OCD I have.

**Comment by Ahwxorg** [comment]
Ah alright! Thanks @codedipper!

**Comment by codedipper** [comment]
@osarthak Hey, there's another LibreY vulnerability <3 https://github.com/Ahwxorg/LibreY/pull/31

**Comment by Ahwxorg** [comment]
@osarthak [LibreY.org](https://librey.org/) returns a 403.

**Comment by osarthak** [comment]
@Ahwxorg No more 403

**Comment by Ahwxorg** [comment]
Thanks for resolving the issue and hosting LibreY <3!

**Pull request closed without merging**
