### PR TITLE
Fix fetching other pages when first page is cached

### PR DESCRIPTION
**Pull request by davidovski**
Fixing issues found in #104. 

In #96 cache was changed to using the text query as the cache key, however this did not account for the page or language. Added those to the key. 

Fixed selecting page on qwant image search.

Looks like the config option for bittorrent trackers is misspelled in the config, so I've fixed that. Added a couple of lines so it still works with old configs. (to be removed in the future)

### CODE REVIEW

**Comment by davidovski** [comment]
@Ahwxorg could you please review this PR. In my opinion I think its ready to merge

**Comment by dehlirious** [comment]
One small fix is necessary
```
PHP Warning:  Undefined property: stdClass::$disable_bittorent_search in LibreY/latest/search.php on line 62; 

```


Sidenote(unrelated):
```
PHP Warning:  file_get_contents(.git/refs/heads/main): Failed to open stream: No such file or directory in /LibreY/x/misc/footer.php on line 11"
```

**Comment by davidovski** [comment]
Done, I'll look into that about the "Latest Commit" text not working if its not a checked out repo, probably an issue for a different day though

**Review by Ahwxorg — COMMENTED** [review]
oops i didnt submit it

**Pull request merged**
