### PR TITLE
Add Serbian Locale.

### PR DESCRIPTION
**Pull request by SectorV5**

### CODE REVIEW

**Review by Ahwxorg — APPROVED** [review]
looks solid!

**Comment by Ahwxorg** [comment]
Isn't Serbian `sr` instead of `rs`?

[Source](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=sr)

**Comment by codedipper** [comment]
> Isn't Serbian `sr` instead of `rs`?

No. https://salsa.debian.org/iso-codes-team/iso-codes/-/raw/main/data/iso_3166-1.json?ref_type=heads

> https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=sr
> langcodes_name.php?iso_639_1=sr

ISO 639 codes are for languages.

**Comment by SectorV5** [comment]
> Isn't Serbian `sr` instead of `rs`?
> 
> [Source](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=sr)

That can't be true because Sr will always give you country of Suriname everywhere, I guess it used to be Sr and now is Rs [Source](https://en.wikipedia.org/wiki/Country_codes_of_Serbia) also check this out: https://github.com/Ahwxorg/LibreY/pull/109/commits/3ce14f7e2d24a76038edde526842726210087d1d we added this instance as Rs and it shows the proper Serbian Emoji.

**Comment by davidovski** [comment]
Tested on chromium and firefox, both seem to work now when changing the language setting within the browser.

**Comment by codedipper** [comment]
> I have no clue where, might have dreamt it lmao, but I think I saw a comment from @codedipper, can't find it anymore though... Can you confirm that `sr` is the correct flag? I think it could maybe also be `rs`, but I have no clue to be honest since they both seem to give Serbian after some further _"LibreY-ing"_...

I realised I was wrong and deleted my comment. `sr` is the correct language tag, and `rs` is the correct country code.

[Source](https://salsa.debian.org/iso-codes-team/iso-codes)

**Comment by codedipper** [comment]
Also, unrelated but holy shit [Firefox has a Debian package again](https://support.mozilla.org/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions).

**Comment by Ahwxorg** [comment]
> Also, unrelated but holy shit [Firefox has a Debian package again](https://support.mozilla.org/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions).

*again*, what did I miss? Haven't been on Debian in a while...

**Comment by Ahwxorg** [comment]
Shall I merge then?

**Comment by davidovski** [comment]
Sorry for the confusion, this PR looks fine to be merged, I was just commenting on further additions that could be added in later PRs

**Comment by SectorV5** [comment]
> Shall I merge then?

Yeah, there doesn't seem anything else that has to be done.

**Pull request merged**
