### PR TITLE
ADD: CZ and SK instance

### PR DESCRIPTION
**Pull request by filip2cz**

### CODE REVIEW

**Comment by Ahwxorg** [comment]
image

You seem to block Tor requests. Any reason why?

**Comment by davidovski** [comment]
Hi, thanks for hosting LibreY! Please could you ensure that the source code modifications for your instance are easily accessible by anyone who is using your instance. Please read [LICENSE](https://github.com/Ahwxorg/LibreY/blob/main/LICENSE) for more information.

Also, is it possible to remove the filtering from tor requests? By blocking tor you are restricting users who wish to stay anonymous from using your service, which goes against the whole idea of LibreX/Y (allowing users to use google via a proxy where they would be blocked otherwise). 

Thanks!

**Comment by Ahwxorg** [comment]
@filip2cz pinging since it has not updated yet.

**Comment by filip2cz** [comment]
I am not host of these instances, I am just using it everyday.

**Comment by Ahwxorg** [comment]
Otherwise I'll send an email to the host to let them know of this.

**Comment by kubo6472** [comment]
@Ahwxorg I'm not the host, but I understand the error you seem to get and from browsing a bit on the host's website (this issue seems to be out of control of their clientele) and probably the best way to reach their technical support contact to possibly enable this globally is to reach out at mrazek@hostliner.cz which is the person listed as the technical support.

**Comment by infoekcz** [comment]
Hello,
I'm the owner of Xoogle.cz. The Czech version of the search engine is based on the open-source LibreX project. I have contacted the authors and they have no problem with my version of the search engine. I did not ask for a place in the list of instances.

I understand that you are bothered by the higher security of the server, but because of the war in Ukraine it is impossible to do otherwise... My sites are under major attacks from Russian IP addresses every day. Deploying higher security for all sites was a necessity.

I myself use Xoogle.cz with VPN services such as ExpressVPN. It is mainly TOR that is blocked, and that is unusable for most normal websites nowadays. It's free, so it's widely abused for various attacks or scams.

Thank you for your understanding,
Adolf Pupik, Xoogle.cz

**Comment by davidovski** [comment]
Hi, thanks for your reply. Unfortunately due to the AGPL licensing of the original project, LibreX, and this fork LibreY, it is required that you provide a copy of the source code to anyone who wishes to use your software. See Section 13: 

> "Notwithstanding any other provision of this License, if you modify the
Program, your modified version must prominently offer all users
interacting with it remotely through a computer network (if your version
supports such interaction) an opportunity to receive the Corresponding
Source of your version by providing access to the Corresponding Source
from a network server at no charge, through some standard or customary
means of facilitating copying of software."

This is the primary part that distinguishes the Affero GPL to the standard GPL. I'm sure there are no issues with releasing your source code, I just think that you should make it a bit more clear that there are modifications and which modifications have been made. Linking your public respository for your changes on the homepage is an easy way to do this and will let people know how you've edited the source code. 

The fact that you are blocking requests to your instance at all is very sad. I don't want to get into politics here, but I do not believe that it is just that anyone should be barred from using free software, especially not based on their IP address or otherwise. I understand that tor is often used for malicious/spam requests, however it is a legitimate tool that can and **is** used by people to circumvent censorship and remain anonymous.  Luckily, these people who are unable to access the internet freely and privately in any other way do have other options: other instances of LibreY that do not impose such restrictions on them. 

While I understand your reasoning, I do not think that it is likely that your instance will be added to the list until these restrictions are lifted. However the lack of accessible source code is a much greater issue that you should attempt to resolve as soon as possible, as failing to do so may lead to legal trouble as this is a direct violation of the license agreement.  

Thanks and have a nice day!

**Comment by infoekcz** [comment]
I don't need to be in the instance list and protecting the site is currently a necessity unfortunately. We do not have internet censorship in the Czech Republic or Slovakia. I hope there will be none here. Xoogle is intended primarily for users from the Czech Republic and Slovakia. 

I certainly have no problem with publishing the source code. After all, LibreX/LibreY is open-source. :) There is already a Github link. I'll put it on the main page of the search engine. :)
https://github.com/infoekcz/xoogle/

I'll be describing all the changes on Github, but also on the Blog.xoogle.cz blog.

**Comment by infoekcz** [comment]
Link placed in the search engine. You can find it under the Czech name "Zdroják". :D

**Comment by davidovski** [comment]
Thank you for sharing the source code! 

From what I can see, your instance is still running most of the code from the outdated [librex](https://github.com/hnhx/librex), you should consider updating to LibreY at some point, as that respository is now inactive and has not recieved any subsequent updates. See [Security](https://github.com/Ahwxorg/LibreY/security) for more information about potential vulnerabilities that have been patched in this fork.

**Comment by infoekcz** [comment]
Thank you for your cooperation and suggestions. I'll check out LibreY. ;)
If I understand correctly, LibreX development is over?

**Comment by davidovski** [comment]
The repository has been seemingly abandoned, with the last commits being over 4 months old. While the codebase still works, any improvements and bug fixes have been taking place within this repository since. 

The aim of LibreY is to simply continue the development of librex, mostly trying to keep inline with its existing design philosophy while aiming to provide a more streamlined experience, especially in regards to issues such as being ratelimited by Google.

**Comment by infoekcz** [comment]
Oh, ok. Thanks for information!
Do you have Telegram?

**Comment by Ahwxorg** [comment]
You can join #librey:ahwx.org on Matrix if there's important issues.

**Pull request closed without merging**
