### PR TITLE
Response HTTP 500 when API error

### PR DESCRIPTION
**Pull request by gnh1201**
When the API is too busy, it responds with an error due to the cooltime setting (I'm using the default value). To handle this as an exception, I needed an appropriate HTTP code.

~I searched for an HTTP response code suitable for LibreY, but I couldn't find one that seemed fitting. I thought that 418 (I'm a teapot), which is a bit of a playful code about not being able to brew coffee, might be the closest in meaning to this situation.~ Let's 500

I would appreciate it if you could review it.

### CODE REVIEW

**Comment by Ahwxorg** [comment]
I am familiar and really like 418, but I think that [500](https://http.cat/500) would be a better fit. I'd have to dive in the code first tho (is on the planning for later day)

**Review by Ahwxorg — CHANGES_REQUESTED** [review]
Can you change the error code from 418 to 500? Then I'll merge it!

**Comment by gnh1201** [comment]
I changed from 418 to 500. Thank you :)

**Review by Ahwxorg — APPROVED** [review]
LGTM

**Pull request merged**
