### PR TITLE
Add default theme config option

### PR DESCRIPTION
**Pull request by davidovski**
Just realised that I had already implemented #135 on a private branch and forgot to mention it or make a PR for it. 

The way I did it was quite hacky just to make it work for my instance but I've just updated it so it should work for any instances

Pretty sure it works well, I tested it with different default themes, and none being set and it seemed to work as expected. 

Just realised that this is a duplicate PR to #139, so if you want we can compare how we've implemented it and get best of both here.

### CODE REVIEW

**Comment by Ahwxorg** [comment]
Is this ready to merge?

**Comment by Ahwxorg** [comment]
seems to be ready

**Review by Ahwxorg — APPROVED** [review]

**Comment by codedipper** [comment]
> seems to be ready

Docker features are missing.

**Comment by kdenaeem** [comment]
@davidovski a bit informal, but drop me a message on whatsapp 07763427954

**Comment by Ahwxorg** [comment]
I can already tell you that that won't happen lmao

**Comment by Ahwxorg** [comment]
I'd say use email/Matrix if you want to contact me at least

**Comment by codedipper** [comment]
> Docker features are missing.
.

**Pull request merged**
